### ISSUE TITLE
Replace `read-pkg-up` with `escalade`

### ISSUE THREAD

**Issue by NMinhNguyen** [ehmicky/get-bin-path#11]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

Reduce the amount of installed dependencies by switching to [`escalade`](https://github.com/lukeed/escalade)

### Describe the solution you'd like

Would you be open to a PR that replaces `read-pkg-up` with [`escalade`](https://github.com/lukeed/escalade)?

### Pull request (optional)

- [X] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @NMinhNguyen,

Thanks a lot for your feedback and sorry for the late response.

Great idea! This is now released in [`7.3.0`](https://github.com/ehmicky/get-bin-path/releases/tag/7.3.0). The size has been reduced by 96% :tada: 

Also, the performance should be a little faster.

@all-contributors Please add @NMinhNguyen for ideas.

**Comment by ehmicky** [comment]
Please add @NMinhNguyen for idea.

**Comment by ehmicky** [comment]
@all-contributors Please add @NMinhNguyen for idea.
