### ISSUE TITLE
`packagejson.directories.bin` isn't considered?

### ISSUE THREAD

**Issue by tmillr** [ehmicky/get-bin-path#12]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

I was looking through your code and it seems that `directories.bin` isn't considered. Is this intentional? My npm skills are a bit rusty, but from what I could gather, `directories.bin` is a valid (and mutually-exclusive) alternative to `bin` for specifying package binaries. I was just wondering why it was left out? I imagine it could potentially be a breaking change to implement now however.

`npm help package.json`

```man
bin
~
~
~
    Note that you can also set the executable files using directories.bin #directoriesbin.

    See npm help folders for more info on executables.
~
~
~

directories.bin
    If you specify a bin directory in directories.bin, all the files in that folder will be added.

    Because of the way the bin directive works, specifying both a bin path and  
    setting  directories.bin  is  an error. If you want to specify individual 
    files, use bin, and for all the files in an existing bin directory, use directories.bin.
```

### Describe the solution you'd like

- include `directories.bin` in search
- determine course of action if both fields exist (the docs explicitly label this as an error, but I think npm and/or node allow it anyway? although I haven't thoroughly tested this)
- if searching dir.bin folder, somehow resolve the bin path

### Pull request (optional)

- [X] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @tmillr,

Thanks for reaching out and sorry for the late reply.

Great idea! I have just added support for `directories.bin` in [`8.0.0`](https://github.com/ehmicky/get-bin-path/releases/tag/8.0.0).

Some details:
  - If both `bin` and `directories.bin` are present, `directories.bin` is ignored
  - If `directories.bin` contains only one file, it is used. Else, the [`name` option](https://github.com/ehmicky/get-bin-path#optionsname) can be used to specify the filename to choose. Else, the `package.json` `name` is used for the same purpose. Else, the first filename (by alphabetical order) is used.

@all-contributors Please add @tmillr for ideas!
