### ISSUE TITLE
Support TypeScript projects by adding type declaration

### ISSUE THREAD

**Issue by kabirbaidhya** [ehmicky/get-bin-path#3]
**Which problem is this feature request solving?**
- Support TypeScript - it doesn't right now. I'm trying out in a TS project and it throws error since it couldn't find the type def file for this package.
   ```ts
   import { getBinPath } from 'get-bin-path';

   const binPath = await getBinPath();
   ```
- This is the error you'll get. 
   ![image](https://user-images.githubusercontent.com/3315763/77799917-e60cdb00-709d-11ea-83da-75a5d0152e8c.png)

**Describe the solution you'd like**
- Add type declaration file.

**Can you submit a pull request?**
- Yes

PR done #4

**Comment by papb** [comment]
I am also facing this issue!

**Comment by kabirbaidhya** [comment]
I have already done a PR https://github.com/ehmicky/get-bin-path/pull/4 for this issue. @ehmicky Any chance you're able to review it? Thanks.

**Comment by ehmicky** [comment]
Just reviewed you PR, sorry for the delay!
